### ISSUE TITLE
Support for `get` to a given file name

### ISSUE THREAD

**Issue by shinmyung0** [patrickcrocker/maven-resource#11]
While using this for fetching snapshot artifacts, I find that due to how snapshot artifacts are named , it is hard to deploy them using something like a cloud foundry manifest because a lot of build packs expect specific file to be specified in the path. This means that even though logically, the pipeline is doing just a `get` from an artifact repo to a `put` to a cf space, you need to have an extra task just to do a renaming. Being able to `get` a resource and have it have a predictable name would be a small but welcomed improvement.

**Comment by patrickcrocker** [comment]
This is generally taken care of by overriding the manifest `path` in your pipeline and using a filename glob to specify your versioned artifact:

Example using [cf-resource](https://github.com/concourse/cf-resource):
``` yaml
jobs:
- name: deploy
  plan:
  - get: source-code
  - get: artifact-milestone
    trigger: true
  - put: cf-env
    params:
      manifest: source-code/manifest.yml
      path: artifact-milestone/example-webapp-*.jar
```
