### ISSUE TITLE
git a snapshot results in pinned version not available

### ISSUE THREAD

**Issue by cah-JimShingler** [patrickcrocker/maven-resource#17]
pinned version {"version":"1.6.0-SNAPSHOT"} is not available

Running Concourse 3.6.0 on OSX

It appears that the issue with check around line 82.  The repo has multiple classifiers(Javadoc, source, and the actual binary).

pipeline to reproduce the problem

```
resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

resources:
- name: springsnapshot
  type: maven-resource
  source:
    url: https://repo.spring.io/release/
    snapshot_url: https://repo.spring.io/snapshot/
    artifact: com.rabbitmq.jms:rabbitmq-jms:jar

jobs:
  - name: promote-spring
    plan:
    - get: springsnapshot
      version: { version: '1.6.0-SNAPSHOT' }
```
